### ISSUE TITLE
New update completely broke this.

### ISSUE THREAD

**Issue by IceLancerSR** [Queuete/ExileApi#176]
They added shader cache on hdd with update.

Nothing works not even life bar on your self, tested everything default. I tested with vulkan and directx sometimes screen would start going black from top left and increase exponentially every second until it envelops entire screen

```
MiscInformation, Render -> System.NullReferenceException: Object reference not set to an instance of an object.
   at MiscInformation.MiscInformation.Render()
   at ExileCore.Shared.PluginWrapper.Render() in /buddy/exileapi/Core/Shared/PluginWrapper.cs:line 208

```

```
[ERR] Error when load plugin (PreloadAlert.dll): System.NullReferenceException: Object reference not set to an instance of an object.
   at ExileCore.Shared.Nodes.ColorNodeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /buddy/exileapi/Core/Shared/Nodes/ColorNodeConverter.cs:line 20
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ExileCore.BaseSettingsPlugin`1._LoadSettings() in /buddy/exileapi/Core/BaseSettingsPlugin.cs:line 51
   at ExileCore.Shared.PluginAutoUpdate.PluginLoader.TryLoadPlugin(Assembly assembly, DirectoryInfo directoryInfo) in /buddy/exileapi/Core/Shared/PluginAutoUpdate/PluginLoader.cs:line 115)
```

[Verbose-20210521.log](https://github.com/Queuete/ExileApi/files/6519553/Verbose-20210521.log)

**Comment by snowhawk04** [comment]
The first error is likely a problem with the UI elements being reordered in the new patch. The second error is a problem with PreloadAlert reading a bad value and you should create an issue in that repo.
