### ISSUE TITLE
Monster icons are not displayed after some time

### ISSUE THREAD

**Issue by APXEOLOG** [Queuete/ExileApi#186]
Hi! I've updated the hud after a long time a few weeks ago and I start to experience an issue,
Initially, everything works fine but after some time (~10 minutes) some monsters are not shown by the HUD. This escalates to the point where not a single monster showed by the HUD anymore after ~15 more minutes. The preload info still works just fine though. I tried to enable/disable some plugins but didn't see any improvements.
Debug Window screenshots:
![Loader_qdSLFj6bsf](https://user-images.githubusercontent.com/254369/119614091-8aa3bd80-be06-11eb-954d-77358ea735c3.png)
![Loader_htMgAEefig](https://user-images.githubusercontent.com/254369/119614124-955e5280-be06-11eb-8bca-d24f9845ce79.png)
![Loader_EISw0iDni1](https://user-images.githubusercontent.com/254369/119614143-9abb9d00-be06-11eb-950b-b71faaf9e3d4.png)
![Loader_9nz1ZDLfzE](https://user-images.githubusercontent.com/254369/119614181-a6a75f00-be06-11eb-8954-5cf985fe5a0e.png)

Settings:
![Loader_zruV9HRNXv](https://user-images.githubusercontent.com/254369/119614207-b030c700-be06-11eb-96b4-7b9280389d0c.png)

No errors in the Logs folder (just some verbose content).

Do you have any suggestions for this problem?

**Comment by Queuete** [comment]
The verbose log is the full log which contains potential errors.
The "Debug Window" is showing only some performance information. You reach roughly 30 fps and your plugins are responsible for this. They take ~30ms to run.
As mentioned in the forum thread EliteBar is known to cause performance issues and therefore is not part of the default plugins anymore: https://github.com/Queuete/ExileApi/blob/master/StaticResources/updateSettings_default.json

**Comment by APXEOLOG** [comment]
@Queuete that plugins is disabled for me but I will try to completely remove it and check.
Spotted some exceptions in the log:
```
2021-05-26 10:01:27.420 +03:00 [VRB] Core -> Checking for update...
2021-05-26 10:03:07.427 +03:00 [VRB] Core -> Checking for update...
2021-05-26 10:04:41.426 +03:00 [ERR] IconsBuilder -> System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ExileCore.PoEMemory.Component.DumpObject() in /buddy/exileapi/Core/PoEMemory/Component.cs:line 23
   at IconsBuilder.MonsterIcon.Update(Entity entity, IconsBuilderSettings settings, Dictionary`2 modIcons)
   at IconsBuilder.IconsBuilder.GenerateIcon(Entity entity)
   at IconsBuilder.IconsBuilder.TickLogic()
2021-05-26 10:04:42.171 +03:00 [ERR] IconsBuilder -> System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ExileCore.PoEMemory.Component.DumpObject() in /buddy/exileapi/Core/PoEMemory/Component.cs:line 23
   at IconsBuilder.MonsterIcon.Update(Entity entity, IconsBuilderSettings settings, Dictionary`2 modIcons)
   at IconsBuilder.IconsBuilder.GenerateIcon(Entity entity)
   at IconsBuilder.IconsBuilder.TickLogic()
2021-05-26 10:04:47.439 +03:00 [VRB] Core -> Checking for update...
2021-05-26 10:06:27.453 +03:00 [VRB] Core -> Checking for update...
2021-05-26 10:07:46.894 +03:00 [INF] PerfTimer =-> Load files from memory (156.3494 ms) Thread #[38]
2021-05-26 10:08:07.464 +03:00 [VRB] Core -> Checking for update...
2021-05-26 10:08:36.981 +03:00 [ERR] GetComponents() ->  => 24F40BDAB80 List: 490055002F0074
2021-05-26 10:08:36.981 +03:00 [ERR] Component list: 20548038375178356. Node: Next: 0 Prev: 0 String: 0 ComponentList: 0
2021-05-26 10:09:46.974 +03:00 [INF] PerfTimer =-> Load files from memory (134.2187 ms) Thread #[20]
2021-05-26 10:09:47.477 +03:00 [VRB] Core -> Checking for update...
2021-05-26 10:10:01.284 +03:00 [ERR] IconsBuilder -> System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ExileCore.PoEMemory.Component.DumpObject() in /buddy/exileapi/Core/PoEMemory/Component.cs:line 23
   at IconsBuilder.MonsterIcon.Update(Entity entity, IconsBuilderSettings settings, Dictionary`2 modIcons)
   at IconsBuilder.IconsBuilder.GenerateIcon(Entity entity)
   at IconsBuilder.IconsBuilder.TickLogic()
2021-05-26 10:11:27.477 +03:00 [VRB] Core -> Checking for update...
2021-05-26 10:11:38.665 +03:00 [ERR] GetComponents() ->  => 24F40BDAB80 List: 490055002F0074
```
```
2021-05-26 10:32:21.184 +03:00 [INF] ObjectMagicProperties read mods error address
2021-05-26 10:32:21.184 +03:00 [ERR] IconsBuilder -> System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ExileCore.PoEMemory.Component.DumpObject() in /buddy/exileapi/Core/PoEMemory/Component.cs:line 23
   at IconsBuilder.MonsterIcon.Update(Entity entity, IconsBuilderSettings settings, Dictionary`2 modIcons)
   at IconsBuilder.IconsBuilder.GenerateIcon(Entity entity)
   at IconsBuilder.IconsBuilder.TickLogic()
2021-05-26 10:32:33.472 +03:00 [INF] Chest debug -> CType:Strongbox Path: Metadata/Chests/StrongBoxes/Strongbox #		Text: Strongbox #		Render Name: Strongbox
2021-05-26 10:32:33.478 +03:00 [INF] Stat: ChestDelayDropsUntilDaemonsFinish = 1
2021-05-26 10:33:07.578 +03:00 [VRB] Core -> Checking for update...
2021-05-26 10:33:47.798 +03:00 [ERR] IconsBuilder -> System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at IconsBuilder.IconsBuilder.TickLogic()
2021-05-26 10:34:47.601 +03:00 [VRB] Core -> Checking for update...
2021-05-26 10:35:51.316 +03:00 [INF] PerfTimer =-> Load files from memory (224.5879 ms) Thread #[34]
```
```
2021-05-26 11:21:27.789 +03:00 [VRB] Core -> Checking for update...
2021-05-26 11:22:58.421 +03:00 [ERR] IconsBuilder -> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match)
   at JM.LinqFaster.LinqFaster.FirstOrDefaultF[T](List`1 source, Predicate`1 predicate)
   at IconsBuilder.MonsterIcon.Update(Entity entity, IconsBuilderSettings settings, Dictionary`2 modIcons)
   at IconsBuilder.IconsBuilder.GenerateIcon(Entity entity)
   at IconsBuilder.IconsBuilder.TickLogic()
2021-05-26 11:23:07.796 +03:00 [VRB] Core -> Checking for update...
2021-05-26 11:24:47.805 +03:00 [VRB] Core -> Checking for update...
2021-05-26 11:26:27.820 +03:00 [VRB] Core -> Checking for update...
2021-05-26 11:27:18.532 +03:00 [INF] PerfTimer =-> Load files from memory (171.708 ms) Thread #[20]
2021-05-26 11:28:07.833 +03:00 [VRB] Core -> Checking for update...
2021-05-26 11:28:36.015 +03:00 [INF] ObjectMagicProperties read mods error address
2021-05-26 11:28:36.015 +03:00 [ERR] IconsBuilder -> System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ExileCore.PoEMemory.Component.DumpObject() in /buddy/exileapi/Core/PoEMemory/Component.cs:line 23
   at IconsBuilder.MonsterIcon.Update(Entity entity, IconsBuilderSettings settings, Dictionary`2 modIcons)
   at IconsBuilder.IconsBuilder.GenerateIcon(Entity entity)
   at IconsBuilder.IconsBuilder.TickLogic()
2021-05-26 11:29:47.840 +03:00 [VRB] Core -> Checking for update...
2021-05-26 11:30:45.186 +03:00 [INF] PerfTimer =-> Load files from memory (180.5141 ms) Thread #[19]
```

**Comment by APXEOLOG** [comment]
Ok, I did a lot of tests and I identified that the issue is related to concurrency. I completely disabled it (core: threads=1, all multithreaded options unchecked; iconsbuilder: multithreaded unchecked; minimapicons: multithreaded unchecked) and everything works perfectly now (tested it for an hour)

**Comment by Queuete** [comment]
Thanks for your additional testing.

This is most likely connected to Coroutines. I am 90% sure deactivating Coroutine Multithread and the specific plugin multi thread options is enough.

Coroutines will be gone after the next big patch, this should completly eliminate this bug aswell.

**Comment by Queuete** [comment]
I will keep this open till after the mentioned update and come back afterwards to check if it still happens.

**Comment by deMathias** [comment]
I have the same problem, but a few seconds after the monster icons dissapear the hud process closes.

![image](https://user-images.githubusercontent.com/47175867/120021175-02324200-bfeb-11eb-95ec-7c7b91f69b45.png)

after mouseover of the icon it dissapears offcourse, but then you have an idea how many times i have to restart the client in the timespan of a few hours. 

sometimes it happens after 5 mins, sometimes after 2 hours. 

Which logs can I give for more info?

**Comment by deMathias** [comment]
The previous update fixed the random crashing for me.
