### ISSUE TITLE
Got  Problem with Memory.ReadAsArray

### ISSUE THREAD

**Issue by training0112** [Queuete/ExileApi#268]
currently got spam logs with new Method Add on 3.16, logs file grow greater 100MB

2021-10-31 05:21:14.306 -02:00 [ERR] ReadAsArray-> A: 0 Size: 0. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ProcessMemoryUtilities.Memory.ProcessMemory.ReadProcessMemoryArray[T](IntPtr handle, IntPtr baseAddress, T[] buffer, Int32 offset, Int32 length)
   at ExileCore.Memory.ReadAsArray[T](Int64 addr, Int32 size) in D:\Clouds\Dropbox\Project\ExileApi\Core\Memory.cs:line 133

**Comment by snowhawk04** [comment]
Are you getting this after shifting into the nightmare in Scourge league? I'm pretty sure entities get re-instanced on each nightmare shift resulting in plugins working entities that shouldn't exist (results in UB).

**Comment by training0112** [comment]
yep, almost time i run deli maps with so many nightmare shift, now i try put a condition to temp fix grow logs
![image](https://user-images.githubusercontent.com/33222114/139620150-7bd35294-5536-4c43-91d7-51cc5648d0f9.png)
